### ISSUE TITLE
Export and import of Dataverses, Datasets and Datafies into CSV files

### ISSUE THREAD

**Issue by skasberger** [gdcc/pyDataverse#11]
Export the metadata of a list of Dataverses, Datasets or Datafiles to a csv file. Header should be the attribute name. one row = one Dataverse, Dataset or Datafile. List must contain only same type of data, not mixtures of Dataverses or Datasets for example.

**Comment by pdurbin** [comment]
I'm interested in the ability to list all datasets and dataverses so I can delete them while iterating on "sample data" code as I mentioned in #21. Currently, I'm calling the "contents" API by using the generic "get_request" method: https://github.com/IQSS/dataverse-sample-data/blob/0630d67ec709f99cd9e9818079d763efaedc682e/destroy_all_dvobjects.py#L10 . I'm happy to create a dedicated issue for first class support for the "contents" API if you'd like. It's documented at http://guides.dataverse.org/en/4.15/api/native-api.html#show-contents-of-a-dataverse

**Comment by jggautier** [comment]
Hi @skasberger. Your reply in [that recent Google Groups thread](https://groups.google.com/forum/#!topic/dataverse-community/h9hBbZZa2oM) about getting all dataset metadata in a repository got me thinking about this issue.

Could you share some more about what you mean by exporting the metadata of a list of Dataverses, Datasets or Datafiles to a csv file, and what you mean by an attribute? Would a dataset's author name metadata be an attribute? How do you imagine this would help people?

Sometimes I field requests for compiling dataset metadata into tabular files, and I'm wondering if this issue is related. For example:

| dataset_id   | publicationdates | authornames | subjects | keywords |
|-----------|-------|----------|--------|------|
| 01957  | 2000-01-01 | Gautier, Julian | Social Science | economics |
| 61008   | 2000-01-02 | Lname, Fname | Agriculature | food  |

**Comment by skasberger** [comment]
@pdurbin Are you interested in an easy query to get all dataverses, datasets or datafiles, or to store such list into a CSV file, or both? doesn't really matter anyway, cause both is working in the develop branch, but wanted to get sure to understand your problem.

**Comment by pdurbin** [comment]
@skasberger my destroy_all_dvobjects.py script mentioned above is working well enough for me. So I'm all set at the moment. Thanks for asking! 😄

**Comment by skasberger** [comment]
The functionality is nearly implemented, let me explain: the write_dicts_as_csv() function in utils.py takes a list of dicts and stores it as CSV. just pass a list of the output from the get() function into it, and its done.

**Comment by skasberger** [comment]
Purpose:
* Mass import of data from CSV files. 
* Use [CSV templates ](https://github.com/AUSSDA/pyDataverse_templates)
* Define standard for CSV format

Data types:
* Dataverse
* Dataset
* Datafile

Functionalities:
* validate (import, export)
* from_csv()
* to_csv()
* check when importing metadata from csv, if column name is unique
* define CSV standard and update pyDataverse templates with it

**Comment by skasberger** [comment]
Implemented in https://github.com/gdcc/pyDataverse/releases/tag/v0.3.0

See: @pdurbin 

- https://pydataverse.readthedocs.io/en/latest/user/csv-templates.html
- https://pydataverse.readthedocs.io/en/latest/user/use-cases.html
- https://pydataverse.readthedocs.io/en/latest/reference.html#pyDataverse.api.NativeApi.get_children
